name: example_new
description: Graphql test
version: 0.0.1
#homepage: https://www.example.com
#author: Thomas Hourlier <email@example.com>

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  graphql_client: ^0.0.3
  graphql_client_generator: ^0.0.0

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.8.0
  build_config: ^0.2.5

dependency_overrides:
  graphql_client:
    path: ../graphql_client
  graphql_client_generator:
    path: ../graphql_client_generator